version: '3.9'

services:

  keycloak:
    container_name: keycloak
    image: jboss/keycloak:11.0.2
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_USER=spring
      - KEYCLOAK_PASSWORD=spring123
    expose:
      - 8888
    ports:
      - 8888:8080


  mongo:
    restart: always
    image: library/mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: "quiz-service"
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin

  gateway:
    container_name: gateway
    image: quiz/gateway:latest
    ports:
      - 8060:8060
    links:
      - keycloak
      - quiz-service


  quiz-service:
    environment:
      - MONGO_URI=mongodb://admin:admin@localhost:27017/admin
    container_name: quiz-service
    image: quiz/quiz-service:latest
    ports:
      - 8090:8090
    expose:
      - 8090  
    links:
      - keycloak   
      